# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 30e2d8c245c9d702e31d7bdbe62f94834677d637625f61669d0e4ccb3e578fd6a0cb52e0dcba69e9d6744f8e4d8e7b9ed17104ef8a2127848230f3c3c4f4b368

test:
  secret_key_base: df93ebff8f8cfd21ec58f912b77f56db856c56512affd35711d9029a251a3f00eb93d8c7468606e32db5f5773e18040555642bcb46395365646e5d9b0974d6dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: df93ebff8f8cfd21ec58f912b77f56db856c56512affd35711d9029a251a3f00eb93d8c7468606e32db5f5773e18040555642bcb46395365646e5d9b0974d6dd
